data:
  data_location: ../data/upload/20250430
elasticsearch:
  host: http://127.0.0.1:9200
  index: my_index
milvus:
  collection_name: Test_one
  host: 127.0.0.1
  index_device: cpu
  index_name: IVF_FLAT
  password: yourpassword
  port: '19530'
  replica_num: 1
  user: haluki
  vector_name: multi_search
redis:
  host: http://127.0.0.1
  port: '6379'
search:
  col_choice: hdbscan
  reorder_strategy: distance
  top_k: 20
system:
  url_split: true
